### ISSUE TITLE
Request for Grade

### ISSUE THREAD

**Issue by aylalab** [aylalab/animal-rescue-website#1]
I spent a lot of time creating this website and going over the plethora of issues that arose when brought into Markbot, but sadly did not have enough time to fix every since accessibility/semantic issue. That being said, I still believe that all my hard work is deserving of a decent grade, which I believe to be an A. I spent a lot of time designing the wireframes based on my UX research, and truly believe that I helped to improve the aesthetics of the Freedom Dog Rescue website. 

Furthermore, I applied everything we learned this semester into my website, such as button animations, svg icons, background patterns, retina images and proper photo preparations, and I also went above and beyond by learning how to code a functioning hamburger menu on mobile screens and other nice animations such as the buttons rising when hovered. I invested a lot of time into coding this website, and overall am really proud with how much I've improved in coding since the start of the semester. 

Although there are still a lot of issues with my website that I wish I could have fixed (such as some spacing issues, contrast issues and the logo icon being too small), I think I gained a lot out of the process of coding it and because of that believe that my efforts are deserving of a good grade.

@charlie-quinn

**Comment by aylalab** [comment]
*Please note that because I couldn't satisfy Markbot, I wasn't able to submit it through there. 

@charlie-quinn

**Comment by aylalab** [comment]
I was able to fix most of the markbot errors except for a few performance and accessibility issues. Thank you so much for giving me the change to fix everything, I really appreciate it! Everything about my request for a grade still stands true, except for the "plethora of issues" from markbot :) 

@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@aylalab ⚠️`Reminder: please close this issue since it has been resolved or expired.`
